{
  "openapi": "3.0.3",
  "info": {
    "title": "API Reference",
    "version": "v0",
    "description": "Sentry Public API"
  },
  "servers": [
    {
      "url": "https://sentry.io"
    }
  ],
  "paths": {
    "/api/0/organizations/": {
      "get": {
        "operationId": "listOrganizations",
        "description": "Return a list of organizations available to the authenticated session in a region.\nThis is particularly useful for requests with a user bound context. For API key-based requests this will only return the organization that belongs to the key.",
        "summary": "List Your Organizations",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "auth_token": [
              "org:admin",
              "org:read",
              "org:write"
            ]
          }
        ]
      }
    },
    "/api/0/organizations/{organization_id_or_slug}/": {
      "get": {
        "operationId": "getOrganization",
        "description": "Return details on an individual organization, including various details\nsuch as membership access and teams.",
        "summary": "Retrieve an Organization",
        "tags": [
          "Organizations"
        ],
        "security": [
          {
            "auth_token": [
              "org:admin",
              "org:read",
              "org:write"
            ]
          }
        ]
      }
    },
    "/api/0/organizations/{organization_id_or_slug}/projects/": {
      "get": {
        "operationId": "listOrganizationProjects",
        "description": "Return a list of projects bound to a organization.",
        "summary": "List an Organization's Projects",
        "tags": [
          "Organizations"
        ],
        "security": [
          {
            "auth_token": [
              "org:admin",
              "org:read",
              "org:write"
            ]
          }
        ]
      }
    },
    "/api/0/organizations/{organization_id_or_slug}/teams/": {
      "get": {
        "operationId": "listOrganizationTeams",
        "description": "Returns a list of teams bound to a organization.",
        "summary": "List an Organization's Teams",
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "auth_token": [
              "org:admin",
              "org:read",
              "org:write"
            ]
          }
        ]
      }
    },
    "/api/0/organizations/{organization_id_or_slug}/members/": {
      "get": {
        "operationId": "listOrganizationMembers",
        "description": "List all organization members.\n\nResponse includes pending invites that are approved by organization owners or managers but waiting to be accepted by the invitee.",
        "summary": "List an Organization's Members",
        "tags": [
          "Organizations"
        ],
        "security": [
          {
            "auth_token": [
              "member:admin",
              "member:read",
              "member:write"
            ]
          }
        ]
      }
    },
    "/api/0/organizations/{organization_id_or_slug}/members/{member_id}/": {
      "get": {
        "operationId": "getOrganizationMember",
        "description": "Retrieve an organization member's details.\n\nResponse will be a pending invite if it has been approved by organization owners or managers but is waiting to be accepted by the invitee.",
        "summary": "Retrieve an Organization Member",
        "tags": [
          "Organizations"
        ],
        "security": [
          {
            "auth_token": [
              "member:admin",
              "member:read",
              "member:write"
            ]
          }
        ]
      }
    },
    "/api/0/teams/{organization_id_or_slug}/{team_id_or_slug}/": {
      "get": {
        "operationId": "getTeam",
        "description": "Return details on an individual team.",
        "summary": "Retrieve a Team",
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "auth_token": [
              "team:admin",
              "team:read",
              "team:write"
            ]
          }
        ]
      }
    },
    "/api/0/teams/{organization_id_or_slug}/{team_id_or_slug}/members/": {
      "get": {
        "operationId": "listTeamMembers",
        "description": "List all members on a team.\n\nThe response will not include members with pending invites.",
        "summary": "List a Team's Members",
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "auth_token": [
              "team:admin",
              "team:read",
              "team:write"
            ]
          }
        ]
      }
    },
    "/api/0/teams/{organization_id_or_slug}/{team_id_or_slug}/projects/": {
      "get": {
        "operationId": "listTeamProjects",
        "description": "Return a list of projects bound to a team.",
        "summary": "List a Team's Projects",
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "auth_token": [
              "project:admin",
              "project:read",
              "project:write"
            ]
          }
        ]
      }
    },
    "/api/0/projects/{organization_id_or_slug}/{project_id_or_slug}/": {
      "get": {
        "operationId": "getProject",
        "description": "Return details on an individual project.",
        "summary": "Retrieve a Project",
        "tags": [
          "Projects"
        ],
        "security": [
          {
            "auth_token": [
              "project:admin",
              "project:read",
              "project:write"
            ]
          }
        ]
      }
    },
    "/api/0/projects/{organization_id_or_slug}/{project_id_or_slug}/teams/": {
      "get": {
        "operationId": "listProjectTeams",
        "description": "Return a list of teams that have access to this project.",
        "summary": "List a Project's Teams",
        "tags": [
          "Teams"
        ],
        "security": [
          {
            "auth_token": [
              "project:admin",
              "project:read",
              "project:write"
            ]
          }
        ]
      }
    },
    "/api/0/projects/{organization_id_or_slug}/{project_id_or_slug}/issues/": {
      "get": {
        "tags": [
          "Events"
        ],
        "description": "**Deprecated**: This endpoint has been replaced with the [Organization Issues endpoint](/api/events/list-an-organizations-issues/) which\nsupports filtering on project and additional functionality.\n\nReturn a list of issues (groups) bound to a project.  All parameters are supplied as query string parameters. \n\n A default query of ``is:unresolved`` is applied. To return results with other statuses send an new query value (i.e. ``?query=`` for all results).\n\nThe ``stat[...]",
        "operationId": "List a Project's Issues",
        "deprecated": true,
        "security": [
          {
            "auth_token": [
              "event:read"
            ]
          }
        ]
      }
    },
    "/api/0/organizations/{organization_id_or_slug}/issues/{issue_id}/": {
      "get": {
        "operationId": "getOrganizationIssue",
        "description": "Return details on an individual issue, including its basic stats, comment\nand user-report counts, and a summary of the latest event.",
        "summary": "Retrieve an Issue",
        "tags": [
          "Events"
        ],
        "security": [
          {
            "auth_token": [
              "event:admin",
              "event:read",
              "event:write"
            ]
          }
        ]
      }
    },
    "/api/0/organizations/{organization_id_or_slug}/issues/{issue_id}/events/": {
      "get": {
        "operationId": "listOrganizationIssueEvents",
        "description": "Return a list of error events bound to an issue",
        "summary": "List an Issue's Events",
        "tags": [
          "Events"
        ],
        "security": [
          {
            "auth_token": [
              "event:admin",
              "event:read",
              "event:write"
            ]
          }
        ]
      }
    },
    "/api/0/organizations/{organization_id_or_slug}/issues/{issue_id}/events/{event_id}/": {
      "get": {
        "operationId": "getOrganizationIssueEvent",
        "description": "Retrieves the details of an issue event.",
        "summary": "Retrieve an Issue Event",
        "tags": [
          "Events"
        ],
        "security": [
          {
            "auth_token": [
              "event:admin",
              "event:read",
              "event:write"
            ]
          }
        ]
      }
    },
    "/api/0/organizations/{organization_id_or_slug}/releases/": {
      "get": {
        "operationId": "listOrganizationReleases",
        "description": "Return a list of releases for a given organization, sorted by most recent.",
        "summary": "List an Organization's Releases",
        "tags": [
          "Releases"
        ],
        "security": [
          {
            "auth_token": [
              "org:ci",
              "project:admin",
              "project:read",
              "project:releases",
              "project:write"
            ]
          }
        ]
      }
    },
    "/api/0/organizations/{organization_id_or_slug}/releases/{version}/": {
      "get": {
        "operationId": "getOrganizationRelease",
        "description": "Return details on an individual release.",
        "summary": "Retrieve an Organization's Release",
        "tags": [
          "Releases"
        ],
        "security": [
          {
            "auth_token": [
              "org:ci",
              "project:admin",
              "project:read",
              "project:releases",
              "project:write"
            ]
          }
        ]
      }
    },
    "/api/0/organizations/{organization_id_or_slug}/releases/{version}/files/": {
      "get": {
        "operationId": "listOrganizationReleaseFiles",
        "description": "Retrieve a list of files for a given release.",
        "summary": "List an Organization's Release Files",
        "tags": [
          "Releases"
        ],
        "security": [
          {
            "auth_token": [
              "org:ci",
              "project:admin",
              "project:read",
              "project:releases",
              "project:write"
            ]
          }
        ]
      }
    },
    "/api/0/organizations/{organization_id_or_slug}/releases/{version}/commits/": {
      "get": {
        "operationId": "listOrganizationReleaseCommits",
        "description": "Retrieve a list of commits for a given release.",
        "summary": "List an Organization Release's Commits",
        "tags": [
          "Releases"
        ],
        "security": [
          {
            "auth_token": [
              "org:ci",
              "project:admin",
              "project:read",
              "project:releases",
              "project:write"
            ]
          }
        ]
      }
    },
    "/api/0/organizations/{organization_id_or_slug}/releases/{version}/deploys/": {
      "get": {
        "operationId": "listOrganizationReleaseDeploys",
        "description": "Returns a list of deploys based on the organization, version, and project.",
        "summary": "List a Release's Deploys",
        "tags": [
          "Releases"
        ],
        "security": [
          {
            "auth_token": [
              "org:ci",
              "project:admin",
              "project:read",
              "project:releases",
              "project:write"
            ]
          }
        ]
      }
    },
    "/api/0/projects/{organization_id_or_slug}/{project_id_or_slug}/stats/": {
      "get": {
        "operationId": "listProjectStats",
        "description": "Return a set of points representing a normalized timestamp and the number of\nevents seen in the period.\n\nQuery ranges are limited to Sentry's configured time-series resolutions.\nThis endpoint may change in the future without notice.",
        "summary": "Retrieve Event Counts for a Project",
        "tags": [
          "Projects"
        ],
        "security": [
          {
            "auth_token": [
              "project:admin",
              "project:read",
              "project:write"
            ]
          }
        ]
      }
    },
    "/api/0/organizations/{organization_id_or_slug}/events/": {
      "get": {
        "operationId": "listOrganizationEvents",
        "description": "Retrieves explore data for a given organization.\n\n**Note**: This endpoint is intended to get a table of results, and is not for doing a full export of data sent to\nSentry.\n\nThe `field` query parameter determines what fields will be selected in the `data` and `meta` keys of the endpoint response.\n- The `data` key contains a list of results row by row that match the `query` made\n- The `meta` key contains information about the response, including the unit or type of t[...]",
        "summary": "Query Explore Events in Table Format",
        "tags": [
          "Explore"
        ],
        "security": [
          {
            "auth_token": [
              "org:admin",
              "org:read",
              "org:write"
            ]
          }
        ]
      }
    },
    "/api/0/organizations/{organization_id_or_slug}/tags/": {
      "get": {
        "operationId": "listOrganizationTags",
        "description": "Return a list of tag keys for the given organization.",
        "summary": "List an Organization's Tags",
        "tags": [
          "Discover"
        ],
        "security": [
          {
            "auth_token": [
              "org:admin",
              "org:read",
              "org:write"
            ]
          }
        ]
      }
    },
    "/api/0/projects/{organization_id_or_slug}/{project_id_or_slug}/keys/": {
      "get": {
        "operationId": "listProjectKeys",
        "description": "Return a list of client keys bound to a project.",
        "summary": "List a Project's Client Keys",
        "tags": [
          "Projects"
        ],
        "security": [
          {
            "auth_token": [
              "project:admin",
              "project:read",
              "project:write"
            ]
          }
        ]
      }
    },
    "/api/0/projects/{organization_id_or_slug}/{project_id_or_slug}/environments/": {
      "get": {
        "operationId": "listProjectEnvironments",
        "description": "Lists a project's environments.",
        "summary": "List a Project's Environments",
        "tags": [
          "Environments"
        ],
        "security": [
          {
            "auth_token": [
              "project:admin",
              "project:read",
              "project:write"
            ]
          }
        ]
      }
    }
  }
}